import json
import logging
import time
import uuid
from contextlib import asynccontextmanager
from os import getenv
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, StreamingResponse
from google.genai import types
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

from adk_agent.agent import get_runner, APP_NAME


# OpenAI-compatible request/response models
class ChatMessage(BaseModel):
    """A message in the conversation."""

    role: str = Field(
        ...,
        description="The role of the message author.",
        examples=["user", "assistant", "system", "tool"],
    )
    content: str = Field(
        ...,
        description="The contents of the message.",
        examples=["What is the best cluster hosting service?"],
    )


class ChatCompletionRequest(BaseModel):
    """Creates a model response for the given chat conversation.

    [See OpenAI docs](https://platform.openai.com/docs/api-reference/chat/create)
    """

    messages: list[ChatMessage] = Field(
        ..., description="A list of messages comprising the conversation so far."
    )
    model: str | None = Field(
        None,
        description="ID of the model to use. Defaults to the server's configured MODEL_ID.",
    )
    stream: bool = Field(
        False,
        description="If true, partial message deltas will be sent as SSE `data: {json}\\n\\n` events, terminated by `data: [DONE]\\n\\n`.",
    )


class ChoiceMessage(BaseModel):
    """A chat completion message generated by the model."""

    role: str = Field(
        "assistant", description="The role of the author of this message."
    )
    content: str = Field(..., description="The contents of the message.")


class Choice(BaseModel):
    index: int = Field(
        ..., description="The index of the choice in the list of choices."
    )
    message: ChoiceMessage
    finish_reason: str = Field(
        ...,
        description="The reason the model stopped generating tokens.",
        examples=["stop", "tool_calls"],
    )


class ChatCompletionResponse(BaseModel):
    """Represents a chat completion response returned by the model, based on the provided input."""

    id: str = Field(
        ...,
        description="A unique identifier for the chat completion.",
        examples=["chatcmpl-abc123def456"],
    )
    object: str = Field(
        "chat.completion",
        description="The object type, which is always `chat.completion`.",
    )
    created: int = Field(
        ...,
        description="The Unix timestamp (in seconds) of when the chat completion was created.",
    )
    model: str = Field(..., description="The model used for the chat completion.")
    choices: list[Choice] = Field(..., description="A list of chat completion choices.")

    usage: dict | None = Field(
        None, description="Usage statistics for the completion request."
    )


class HealthResponse(BaseModel):
    """Service health status."""

    status: str = Field(
        ..., description="Current service status.", examples=["healthy"]
    )
    agent_initialized: bool = Field(
        ...,
        description="Whether the agent has been initialized and is ready to serve requests.",
    )


# Global variables
runner = None
USER_ID = "api_user"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize the ADK agent runner on startup and clear it on shutdown."""
    global runner

    base_url = getenv("BASE_URL")
    model_id = getenv("MODEL_ID")

    if base_url:
        base_url = base_url.rstrip("/")
        if not base_url.endswith("/v1"):
            base_url += "/v1"

    runner = get_runner(model_id=model_id, base_url=base_url)

    yield

    runner = None


# Create FastAPI app
app = FastAPI(
    title="Google ADK Agent API",
    description="FastAPI service for Google ADK 2.0 Agent with OpenAI-compatible chat completions API.",
    lifespan=lifespan,
    openapi_tags=[
        {"name": "Chat", "description": "Chat completion operations"},
        {"name": "Health", "description": "Service health monitoring"},
    ],
)


def _make_completion_id() -> str:
    return f"chatcmpl-{uuid.uuid4().hex[:12]}"


def _extract_user_message(messages: list[ChatMessage]) -> str:
    """Extract the last user message content from the OpenAI-format messages list."""
    for msg in reversed(messages):
        if msg.role == "user":
            return msg.content
    raise HTTPException(
        status_code=400, detail="No user message found in messages list"
    )


def _extract_text_from_events(events: list) -> str:
    """Extract the final text response from ADK events."""
    final_text = ""
    for event in events:
        if event.content and event.content.parts:
            for part in event.content.parts:
                if part.text:
                    final_text = part.text
    return final_text


@app.post(
    "/chat/completions",
    response_model=ChatCompletionResponse,
    summary="Create chat completion",
    description="Creates a model response for the given chat conversation. When `stream=false`, returns a complete `chat.completion` JSON object. When `stream=true`, returns Server-Sent Events with `chat.completion.chunk` deltas.",
    tags=["Chat"],
)
async def chat_completions(request: ChatCompletionRequest):
    global runner

    if runner is None:
        raise HTTPException(status_code=503, detail="Agent not initialized")

    user_content = _extract_user_message(request.messages)
    model_id = request.model or getenv("MODEL_ID", "model")

    if request.stream:
        return await _handle_stream(user_content, model_id)
    else:
        return await _handle_chat(user_content, model_id)


async def _handle_chat(user_content: str, model_id: str):
    """Handle non-streaming chat completion."""
    global runner

    try:
        # Create a new session for each request
        session = await runner.session_service.create_session(
            app_name=APP_NAME, user_id=USER_ID
        )

        new_message = types.Content(
            role="user", parts=[types.Part.from_text(text=user_content)]
        )

        # Collect all events
        final_text = ""
        context_messages = []

        async for event in runner.run_async(
            user_id=USER_ID,
            session_id=session.id,
            new_message=new_message,
        ):
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.function_call:
                        context_messages.append(
                            {
                                "role": "assistant",
                                "content": f"Calling tool: {part.function_call.name}",
                                "tool_calls": [
                                    {
                                        "type": "function",
                                        "function": {
                                            "name": part.function_call.name,
                                            "arguments": json.dumps(
                                                dict(part.function_call.args) if part.function_call.args else {}
                                            ),
                                        },
                                    }
                                ],
                            }
                        )
                    elif part.function_response:
                        context_messages.append(
                            {
                                "role": "tool",
                                "name": part.function_response.name,
                                "content": json.dumps(
                                    dict(part.function_response.response) if part.function_response.response else {}
                                ),
                            }
                        )
                    elif part.text:
                        role = event.content.role or "model"
                        context_messages.append(
                            {"role": "assistant" if role == "model" else role, "content": part.text}
                        )
                        if role == "model":
                            final_text = part.text

        return {
            "id": _make_completion_id(),
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model_id,
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": final_text,
                    },
                    "finish_reason": "stop",
                }
            ],
            "context": context_messages,
            "usage": None,
        }

    except Exception:
        logger.exception("Error processing chat completion request")
        raise HTTPException(
            status_code=500, detail="Internal server error"
        )


async def _handle_stream(user_content: str, model_id: str):
    """Handle streaming chat completion with OpenAI-compatible SSE chunks."""
    global runner

    completion_id = _make_completion_id()
    created = int(time.time())

    async def event_generator():
        try:
            session = await runner.session_service.create_session(
                app_name=APP_NAME, user_id=USER_ID
            )

            new_message = types.Content(
                role="user", parts=[types.Part.from_text(text=user_content)]
            )

            async for event in runner.run_async(
                user_id=USER_ID,
                session_id=session.id,
                new_message=new_message,
            ):
                if not event.content or not event.content.parts:
                    continue

                for part in event.content.parts:
                    if part.function_call:
                        data = {
                            "id": completion_id,
                            "object": "chat.completion.chunk",
                            "created": created,
                            "model": model_id,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {
                                        "role": "assistant",
                                        "tool_calls": [
                                            {
                                                "index": 0,
                                                "type": "function",
                                                "function": {
                                                    "name": part.function_call.name,
                                                    "arguments": json.dumps(
                                                        dict(part.function_call.args) if part.function_call.args else {}
                                                    ),
                                                },
                                            }
                                        ],
                                    },
                                    "finish_reason": None,
                                }
                            ],
                        }
                        yield f"data: {json.dumps(data)}\n\n"

                    elif part.function_response:
                        data = {
                            "id": completion_id,
                            "object": "chat.completion.chunk",
                            "created": created,
                            "model": model_id,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {
                                        "role": "tool",
                                        "content": json.dumps(
                                            dict(part.function_response.response) if part.function_response.response else {}
                                        ),
                                        "name": part.function_response.name,
                                    },
                                    "finish_reason": None,
                                }
                            ],
                        }
                        yield f"data: {json.dumps(data)}\n\n"

                    elif part.text:
                        data = {
                            "id": completion_id,
                            "object": "chat.completion.chunk",
                            "created": created,
                            "model": model_id,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {"content": part.text},
                                    "finish_reason": None,
                                }
                            ],
                        }
                        yield f"data: {json.dumps(data)}\n\n"

            # Send final chunk with finish_reason
            final_data = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": model_id,
                "choices": [
                    {
                        "index": 0,
                        "delta": {},
                        "finish_reason": "stop",
                    }
                ],
            }
            yield f"data: {json.dumps(final_data)}\n\n"
            yield "data: [DONE]\n\n"

        except Exception:
            logger.exception("Error in stream event_generator")
            error_data = {
                "error": {
                    "message": "Internal server error",
                    "type": "server_error",
                }
            }
            yield f"data: {json.dumps(error_data)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.get(
    "/health", response_model=HealthResponse, summary="Health check", tags=["Health"]
)
async def health():
    return {"status": "healthy", "agent_initialized": runner is not None}


# ── Playground UI ────────────────────────────────────────────────────────────
_BASE_DIR = Path(__file__).resolve().parent
_PLAYGROUND_HTML = _BASE_DIR / "playground" / "templates" / "index.html"
# In Docker the images are copied to /opt/app-root/src/images; locally they live at the repo root
_IMAGES_DIR = _BASE_DIR / "images"
if not _IMAGES_DIR.is_dir():
    _IMAGES_DIR = _BASE_DIR.parent.parent.parent / "images"


@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def playground():
    """Serve the playground chat UI."""
    return FileResponse(
        _PLAYGROUND_HTML,
        headers={"Cache-Control": "no-cache, no-store, must-revalidate"},
    )


@app.get("/images/{filename:path}", include_in_schema=False)
async def serve_image(filename: str):
    """Serve images from the project-level images directory."""
    if Path(filename).is_absolute():
        raise HTTPException(status_code=404, detail="Image not found")
    base = _IMAGES_DIR.resolve()
    file_path = (base / filename).resolve()
    try:
        file_path.relative_to(base)
    except ValueError:
        raise HTTPException(status_code=404, detail="Image not found")
    if not file_path.is_file():
        raise HTTPException(status_code=404, detail="Image not found")
    return FileResponse(file_path)


if __name__ == "__main__":
    import uvicorn

    port = int(getenv("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
