target-version = "py312"
line-length = 88

[lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[format]
quote-style = "double"
line-ending = "auto"

exclude = [
    ".git",
    ".venv",
    "venv",
    "build",
    "__pycache__",
    "site-packages",
    "*.egg-info",
]
