target-version = "py312"
line-length = 88

[lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[lint.per-file-ignores]
"**/main.py" = ["E402"]
"**/examples/**" = ["E402"]
"**/tests/**" = ["E402"]
"**/mcp_automl_template/**" = ["E402"]

[format]
quote-style = "double"
line-ending = "auto"

exclude = [
    ".git",
    ".venv",
    "venv",
    "build",
    "__pycache__",
    "site-packages",
    "*.egg-info",
]
