---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencode-web
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.opencode-web: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"opencode-web"}}'
