apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests

namespace: opencode

patches:
  - path: deployment-patch.yaml
  - path: remove-route.yaml
  - path: remove-service.yaml
