apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests

namespace: YOUR-NAMESPACE

patches:
  - target:
      kind: Deployment
      name: opencode-web
    path: deployment-patch.yaml

  - target:
      kind: ConfigMap
      name: opencode-web-entrypoint
    path: entrypoint-patch.yaml
