{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.secretName" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secret.apiKey | b64enc | quote }}
{{- end }}
