{{- if .Values.secrets.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-secret
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
{{- end }}
