import json
import logging
import time
import uuid
from contextlib import asynccontextmanager
from os import getenv

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

from react_agent.agent import get_graph_closure


# OpenAI-compatible request/response models
class ChatMessage(BaseModel):
    """A message in the conversation."""

    role: str = Field(
        ...,
        description="The role of the message author.",
        examples=["user", "assistant", "system", "tool"],
    )
    content: str = Field(
        ...,
        description="The contents of the message.",
        examples=["What is the best cluster hosting service?"],
    )


class ChatCompletionRequest(BaseModel):
    """Creates a model response for the given chat conversation.

    [See OpenAI docs](https://platform.openai.com/docs/api-reference/chat/create)
    """

    messages: list[ChatMessage] = Field(
        ..., description="A list of messages comprising the conversation so far."
    )
    model: str | None = Field(
        None,
        description="ID of the model to use. Defaults to the server's configured MODEL_ID.",
    )
    stream: bool = Field(
        False,
        description="If true, partial message deltas will be sent as SSE `data: {json}\\n\\n` events, terminated by `data: [DONE]\\n\\n`.",
    )


class ChoiceMessage(BaseModel):
    """A chat completion message generated by the model."""

    role: str = Field(
        "assistant", description="The role of the author of this message."
    )
    content: str = Field(..., description="The contents of the message.")


class Choice(BaseModel):
    index: int = Field(
        ..., description="The index of the choice in the list of choices."
    )
    message: ChoiceMessage
    finish_reason: str = Field(
        ...,
        description="The reason the model stopped generating tokens.",
        examples=["stop", "tool_calls"],
    )


class ChatCompletionResponse(BaseModel):
    """Represents a chat completion response returned by the model, based on the provided input."""

    id: str = Field(
        ...,
        description="A unique identifier for the chat completion.",
        examples=["chatcmpl-abc123def456"],
    )
    object: str = Field(
        "chat.completion",
        description="The object type, which is always `chat.completion`.",
    )
    created: int = Field(
        ...,
        description="The Unix timestamp (in seconds) of when the chat completion was created.",
    )
    model: str = Field(..., description="The model used for the chat completion.")
    choices: list[Choice] = Field(..., description="A list of chat completion choices.")

    usage: dict | None = Field(
        None, description="Usage statistics for the completion request."
    )


class HealthResponse(BaseModel):
    """Service health status."""

    status: str = Field(
        ..., description="Current service status.", examples=["healthy"]
    )
    agent_initialized: bool = Field(
        ...,
        description="Whether the agent has been initialized and is ready to serve requests.",
    )


# Global variable for agent graph
agent_graph = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize the ReAct agent graph on startup and clear it on shutdown."""
    global agent_graph

    base_url = getenv("BASE_URL")
    model_id = getenv("MODEL_ID")

    if base_url and not base_url.endswith("/v1"):
        base_url = base_url.rstrip("/") + "/v1"

    agent_graph = get_graph_closure(model_id=model_id, base_url=base_url)

    yield

    agent_graph = None


# Create FastAPI app
app = FastAPI(
    title="LangGraph React Agent API",
    description="FastAPI service for LangGraph React Agent with OpenAI-compatible chat completions API.",
    lifespan=lifespan,
    openapi_tags=[
        {"name": "Chat", "description": "Chat completion operations"},
        {"name": "Health", "description": "Service health monitoring"},
    ],
)


def _build_langchain_messages(messages: list[ChatMessage]) -> list[HumanMessage]:
    """Extract the last user message from the OpenAI-format messages list."""
    for msg in reversed(messages):
        if msg.role == "user":
            return [HumanMessage(content=msg.content)]
    raise ValueError("No user message found in messages list")


def _make_completion_id() -> str:
    return f"chatcmpl-{uuid.uuid4().hex[:12]}"


@app.post(
    "/chat/completions",
    response_model=ChatCompletionResponse,
    summary="Create chat completion",
    description="Creates a model response for the given chat conversation. When `stream=false`, returns a complete `chat.completion` JSON object. When `stream=true`, returns Server-Sent Events with `chat.completion.chunk` deltas.",
    tags=["Chat"],
)
async def chat_completions(request: ChatCompletionRequest):
    global agent_graph

    if agent_graph is None:
        raise HTTPException(status_code=503, detail="Agent not initialized")

    langchain_messages = _build_langchain_messages(request.messages)
    model_id = request.model or getenv("MODEL_ID", "model")

    if request.stream:
        return await _handle_stream(langchain_messages, model_id)
    else:
        return await _handle_chat(langchain_messages, model_id)


async def _handle_chat(messages: list[HumanMessage], model_id: str):
    """Handle non-streaming chat completion."""
    global agent_graph

    try:
        result = await agent_graph.ainvoke(
            {"messages": messages}, config={"recursion_limit": 10}
        )

        # Extract the final assistant message content
        assistant_content = ""
        context_messages = []

        if "messages" in result and len(result["messages"]) > 0:
            for message in result["messages"]:
                if isinstance(message, HumanMessage):
                    context_messages.append(
                        {"role": "user", "content": message.content}
                    )
                elif isinstance(message, AIMessage):
                    msg_data = {"role": "assistant", "content": message.content or ""}
                    if message.tool_calls:
                        msg_data["tool_calls"] = [
                            {
                                "id": tc["id"],
                                "type": "function",
                                "function": {
                                    "name": tc["name"],
                                    "arguments": json.dumps(tc["args"]),
                                },
                            }
                            for tc in message.tool_calls
                        ]
                    context_messages.append(msg_data)
                elif isinstance(message, ToolMessage):
                    context_messages.append(
                        {
                            "role": "tool",
                            "tool_call_id": message.tool_call_id,
                            "name": message.name,
                            "content": message.content,
                        }
                    )

            # Final assistant content is the last AIMessage with content
            for message in reversed(result["messages"]):
                if isinstance(message, AIMessage) and message.content:
                    assistant_content = message.content
                    break

        return {
            "id": _make_completion_id(),
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model_id,
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": assistant_content,
                    },
                    "finish_reason": "stop",
                }
            ],
            "context": context_messages,
            "usage": None,
        }

    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Error processing request: {str(e)}"
        )


async def _handle_stream(messages: list[HumanMessage], model_id: str):
    """Handle streaming chat completion with OpenAI-compatible SSE chunks."""
    global agent_graph

    completion_id = _make_completion_id()
    created = int(time.time())

    async def event_generator():
        try:
            async for event in agent_graph.astream_events(
                {"messages": messages},
                config={"recursion_limit": 10},
                version="v2",
            ):
                kind = event["event"]

                # LLM streaming tokens
                if kind == "on_chat_model_stream":
                    chunk = event["data"]["chunk"]
                    if chunk.content:
                        data = {
                            "id": completion_id,
                            "object": "chat.completion.chunk",
                            "created": created,
                            "model": model_id,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {"content": chunk.content},
                                    "finish_reason": None,
                                }
                            ],
                        }
                        yield f"data: {json.dumps(data)}\n\n"

                # Tool calls (after LLM finishes generating the call)
                elif kind == "on_chat_model_end":
                    message = event["data"]["output"]
                    if hasattr(message, "tool_calls") and message.tool_calls:
                        tool_calls_delta = [
                            {
                                "index": i,
                                "id": tc["id"],
                                "type": "function",
                                "function": {
                                    "name": tc["name"],
                                    "arguments": json.dumps(tc["args"]),
                                },
                            }
                            for i, tc in enumerate(message.tool_calls)
                        ]
                        data = {
                            "id": completion_id,
                            "object": "chat.completion.chunk",
                            "created": created,
                            "model": model_id,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {
                                        "role": "assistant",
                                        "tool_calls": tool_calls_delta,
                                    },
                                    "finish_reason": None,
                                }
                            ],
                        }
                        yield f"data: {json.dumps(data)}\n\n"

                # Tool execution results
                elif kind == "on_tool_end":
                    output = event["data"].get("output", "")
                    if hasattr(output, "content"):
                        output = output.content
                    data = {
                        "id": completion_id,
                        "object": "chat.completion.chunk",
                        "created": created,
                        "model": model_id,
                        "choices": [
                            {
                                "index": 0,
                                "delta": {
                                    "role": "tool",
                                    "content": str(output),
                                    "name": event.get("name", ""),
                                },
                                "finish_reason": None,
                            }
                        ],
                    }
                    yield f"data: {json.dumps(data)}\n\n"

            # Send final chunk with finish_reason
            final_data = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": model_id,
                "choices": [
                    {
                        "index": 0,
                        "delta": {},
                        "finish_reason": "stop",
                    }
                ],
            }
            yield f"data: {json.dumps(final_data)}\n\n"
            yield "data: [DONE]\n\n"

        except Exception:
            logger.exception("Error in stream event_generator")
            error_data = {
                "error": {
                    "message": "Internal server error",
                    "type": "server_error",
                }
            }
            yield f"data: {json.dumps(error_data)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.get(
    "/health", response_model=HealthResponse, summary="Health check", tags=["Health"]
)
async def health():
    return {"status": "healthy", "agent_initialized": agent_graph is not None}


if __name__ == "__main__":
    import uvicorn

    port = int(getenv("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)
