import json
import logging
import time
import uuid
from contextlib import asynccontextmanager
from os import getenv
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, StreamingResponse
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import Command
from pydantic import BaseModel, Field

from human_in_the_loop.agent import get_graph_closure
from human_in_the_loop.tracing import enable_tracing

logger = logging.getLogger(__name__)


# OpenAI-compatible request/response models
class ChatMessage(BaseModel):
    """A message in the conversation."""

    role: str = Field(
        ...,
        description="The role of the message author.",
        examples=["user", "assistant", "system", "tool"],
    )
    content: str = Field(
        ...,
        description="The contents of the message.",
        examples=["Create a file called report.md with info about LangChain"],
    )


class ChatCompletionRequest(BaseModel):
    """Creates a model response for the given chat conversation.

    [See OpenAI docs](https://platform.openai.com/docs/api-reference/chat/create)
    """

    messages: list[ChatMessage] = Field(
        ..., description="A list of messages comprising the conversation so far."
    )
    model: str | None = Field(
        None,
        description="ID of the model to use. Defaults to the server's configured MODEL_ID.",
    )
    stream: bool = Field(
        False,
        description="If true, partial message deltas will be sent as SSE `data: {json}\\n\\n` events, terminated by `data: [DONE]\\n\\n`.",
    )
    thread_id: str | None = Field(
        None,
        description="Thread ID for conversation persistence. Required for human-in-the-loop approval flows.",
    )
    approval: str | None = Field(
        None,
        description="Human approval response for a pending tool call. Use 'yes' to approve or 'no' to reject.",
    )


class ChoiceMessage(BaseModel):
    """A chat completion message generated by the model."""

    role: str = Field(
        "assistant", description="The role of the author of this message."
    )
    content: str = Field(..., description="The contents of the message.")


class Choice(BaseModel):
    index: int = Field(
        ..., description="The index of the choice in the list of choices."
    )
    message: ChoiceMessage
    finish_reason: str = Field(
        ...,
        description="The reason the model stopped generating tokens.",
        examples=["stop", "tool_calls", "pending_approval"],
    )


class ChatCompletionResponse(BaseModel):
    """Represents a chat completion response returned by the model, based on the provided input."""

    id: str = Field(
        ...,
        description="A unique identifier for the chat completion.",
        examples=["chatcmpl-abc123def456"],
    )
    object: str = Field(
        "chat.completion",
        description="The object type, which is always `chat.completion`.",
    )
    created: int = Field(
        ...,
        description="The Unix timestamp (in seconds) of when the chat completion was created.",
    )
    model: str = Field(..., description="The model used for the chat completion.")
    choices: list[Choice] = Field(..., description="A list of chat completion choices.")
    thread_id: str | None = Field(
        None,
        description="Thread ID for conversation persistence. Use this to continue the conversation or send approval.",
    )
    usage: dict | None = Field(
        None, description="Usage statistics for the completion request."
    )


class HealthResponse(BaseModel):
    """Service health status."""

    status: str = Field(
        ..., description="Current service status.", examples=["healthy"]
    )
    agent_initialized: bool = Field(
        ...,
        description="Whether the agent has been initialized and is ready to serve requests.",
    )


# Global variables
agent_graph_closure = None
checkpointer = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize the HITL agent graph on startup and clear it on shutdown."""
    global agent_graph_closure, checkpointer

    enable_tracing()

    base_url = getenv("BASE_URL")
    model_id = getenv("MODEL_ID")

    if base_url and not base_url.endswith("/v1"):
        base_url = base_url.rstrip("/") + "/v1"

    checkpointer = MemorySaver()
    agent_graph_closure = get_graph_closure(model_id=model_id, base_url=base_url)

    yield

    agent_graph_closure = None
    checkpointer = None


# Create FastAPI app
app = FastAPI(
    title="LangGraph Human-in-the-Loop Agent API",
    description="FastAPI service for a LangGraph agent with Human-in-the-Loop approval. "
    "Tool calls (e.g. create_file) are paused for human review before execution.",
    lifespan=lifespan,
    openapi_tags=[
        {"name": "Chat", "description": "Chat completion operations"},
        {"name": "Health", "description": "Service health monitoring"},
    ],
)


def _build_langchain_messages(messages: list[ChatMessage]) -> list[HumanMessage]:
    """Extract the last user message from the OpenAI-format messages list."""
    for msg in reversed(messages):
        if msg.role == "user":
            return [HumanMessage(content=msg.content)]
    raise ValueError("No user message found in messages list")


def _make_completion_id() -> str:
    return f"chatcmpl-{uuid.uuid4().hex[:12]}"


def _format_context_messages(messages) -> list[dict]:
    """Convert LangChain messages to OpenAI-compatible context dicts."""
    context = []
    for message in messages:
        if isinstance(message, HumanMessage):
            context.append({"role": "user", "content": message.content})
        elif isinstance(message, AIMessage):
            msg_data = {"role": "assistant", "content": message.content or ""}
            if message.tool_calls:
                msg_data["tool_calls"] = [
                    {
                        "id": tc["id"],
                        "type": "function",
                        "function": {
                            "name": tc["name"],
                            "arguments": json.dumps(tc["args"]),
                        },
                    }
                    for tc in message.tool_calls
                ]
            context.append(msg_data)
        elif isinstance(message, ToolMessage):
            context.append(
                {
                    "role": "tool",
                    "tool_call_id": message.tool_call_id,
                    "name": message.name,
                    "content": message.content,
                }
            )
    return context


@app.post(
    "/chat/completions",
    response_model=ChatCompletionResponse,
    summary="Create chat completion",
    description=(
        "Creates a model response for the given chat conversation. "
        "When the agent needs to call a sensitive tool, it pauses and returns "
        "finish_reason='pending_approval' with the tool call details. "
        "To resume, send a follow-up request with the same thread_id and "
        "approval='yes' or approval='no'."
    ),
    tags=["Chat"],
)
async def chat_completions(request: ChatCompletionRequest):
    global agent_graph_closure, checkpointer

    if agent_graph_closure is None:
        raise HTTPException(status_code=503, detail="Agent not initialized")

    thread_id = request.thread_id or uuid.uuid4().hex
    model_id = request.model or getenv("MODEL_ID", "model")
    config = {"configurable": {"thread_id": thread_id}}

    if request.stream:
        return await _handle_stream(request, model_id, thread_id, config)
    else:
        return await _handle_chat(request, model_id, thread_id, config)


async def _handle_chat(
    request: ChatCompletionRequest,
    model_id: str,
    thread_id: str,
    config: dict,
):
    """Handle non-streaming chat completion with HITL support."""
    global agent_graph_closure, checkpointer

    try:
        agent = agent_graph_closure(checkpointer)

        if request.approval:
            # Resume from interrupt with human decision
            if request.approval.lower() in ("yes", "y", "approve"):
                resume_value = {"decisions": [{"type": "approve"}]}
            else:
                resume_value = {
                    "decisions": [
                        {"type": "reject", "message": "User rejected the tool call."}
                    ]
                }
            result = await agent.ainvoke(
                Command(resume=resume_value),
                config=config,
                version="v2",
            )
        else:
            # New conversation turn
            langchain_messages = _build_langchain_messages(request.messages)
            result = await agent.ainvoke(
                {"messages": langchain_messages},
                config=config,
                version="v2",
            )

        # Check if the graph was interrupted (pending human approval)
        if result.interrupts:
            interrupt_value = result.interrupts[0].value

            return {
                "id": _make_completion_id(),
                "object": "chat.completion",
                "created": int(time.time()),
                "model": model_id,
                "choices": [
                    {
                        "index": 0,
                        "message": {
                            "role": "assistant",
                            "content": json.dumps(interrupt_value),
                        },
                        "finish_reason": "pending_approval",
                    }
                ],
                "thread_id": thread_id,
                "usage": None,
            }

        all_messages = result.value.get("messages", [])

        # Extract the final assistant content
        assistant_content = ""
        for message in reversed(all_messages):
            if isinstance(message, AIMessage) and message.content:
                assistant_content = message.content
                break

        context_messages = _format_context_messages(all_messages)

        return {
            "id": _make_completion_id(),
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model_id,
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": assistant_content,
                    },
                    "finish_reason": "stop",
                }
            ],
            "context": context_messages,
            "thread_id": thread_id,
            "usage": None,
        }

    except Exception:
        logger.exception("Error processing chat completion request")
        raise HTTPException(
            status_code=500, detail="Internal server error"
        )


async def _handle_stream(
    request: ChatCompletionRequest,
    model_id: str,
    thread_id: str,
    config: dict,
):
    """Handle streaming chat completion with HITL support.

    Uses astream with stream_mode="updates" to detect __interrupt__ keys
    in the stream, which is the recommended approach per LangGraph docs.

    NOTE: stream_mode="updates" yields complete node outputs (full messages)
    rather than token-by-token chunks. For true token-level streaming, use
    stream_mode=["messages", "updates"] — "messages" provides individual
    tokens while "updates" still allows detecting __interrupt__ events for
    the HITL approval flow. This would require refactoring the chunk
    processing loop below to handle both stream modes.
    """
    global agent_graph_closure, checkpointer

    completion_id = _make_completion_id()
    created = int(time.time())

    async def event_generator():
        try:
            agent = agent_graph_closure(checkpointer)

            if request.approval:
                if request.approval.lower() in ("yes", "y", "approve"):
                    resume_value = {"decisions": [{"type": "approve"}]}
                else:
                    resume_value = {
                        "decisions": [
                            {
                                "type": "reject",
                                "message": "User rejected the tool call.",
                            }
                        ]
                    }
                input_data = Command(resume=resume_value)
            else:
                langchain_messages = _build_langchain_messages(request.messages)
                input_data = {"messages": langchain_messages}

            interrupted = False
            first_chunk = True

            async for chunk in agent.astream(
                input_data,
                config=config,
                stream_mode="updates",
            ):
                # Check for interrupt in the stream update
                if "__interrupt__" in chunk:
                    interrupt_info = chunk["__interrupt__"]
                    interrupt_value = interrupt_info[0].value if interrupt_info else {}
                    data = {
                        "id": completion_id,
                        "object": "chat.completion.chunk",
                        "created": created,
                        "model": model_id,
                        "choices": [
                            {
                                "index": 0,
                                "delta": {
                                    "role": "assistant",
                                    "content": json.dumps(interrupt_value),
                                },
                                "finish_reason": "pending_approval",
                            }
                        ],
                        "thread_id": thread_id,
                    }
                    yield f"data: {json.dumps(data)}\n\n"
                    interrupted = True
                    continue

                # Process node updates containing messages
                for node_name, node_data in chunk.items():
                    if not isinstance(node_data, dict) or "messages" not in node_data:
                        continue

                    msgs = node_data["messages"]
                    if not isinstance(msgs, list):
                        msgs = [msgs]

                    for msg in msgs:
                        if isinstance(msg, AIMessage):
                            if msg.tool_calls:
                                tool_calls_delta = [
                                    {
                                        "index": i,
                                        "id": tc["id"],
                                        "type": "function",
                                        "function": {
                                            "name": tc["name"],
                                            "arguments": json.dumps(tc["args"]),
                                        },
                                    }
                                    for i, tc in enumerate(msg.tool_calls)
                                ]
                                data = {
                                    "id": completion_id,
                                    "object": "chat.completion.chunk",
                                    "created": created,
                                    "model": model_id,
                                    "choices": [
                                        {
                                            "index": 0,
                                            "delta": {
                                                "role": "assistant",
                                                "tool_calls": tool_calls_delta,
                                            },
                                            "finish_reason": None,
                                        }
                                    ],
                                }
                                if first_chunk:
                                    data["thread_id"] = thread_id
                                    first_chunk = False
                                yield f"data: {json.dumps(data)}\n\n"

                            if msg.content:
                                data = {
                                    "id": completion_id,
                                    "object": "chat.completion.chunk",
                                    "created": created,
                                    "model": model_id,
                                    "choices": [
                                        {
                                            "index": 0,
                                            "delta": {"content": msg.content},
                                            "finish_reason": None,
                                        }
                                    ],
                                }
                                if first_chunk:
                                    data["thread_id"] = thread_id
                                    first_chunk = False
                                yield f"data: {json.dumps(data)}\n\n"

                        elif isinstance(msg, ToolMessage):
                            data = {
                                "id": completion_id,
                                "object": "chat.completion.chunk",
                                "created": created,
                                "model": model_id,
                                "choices": [
                                    {
                                        "index": 0,
                                        "delta": {
                                            "role": "tool",
                                            "content": msg.content,
                                            "name": msg.name or "",
                                        },
                                        "finish_reason": None,
                                    }
                                ],
                            }
                            if first_chunk:
                                data["thread_id"] = thread_id
                                first_chunk = False
                            yield f"data: {json.dumps(data)}\n\n"

            # Send final chunk
            final_finish = "pending_approval" if interrupted else "stop"
            final_data = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": model_id,
                "choices": [
                    {
                        "index": 0,
                        "delta": {},
                        "finish_reason": final_finish,
                    }
                ],
            }
            if interrupted:
                final_data["thread_id"] = thread_id
            yield f"data: {json.dumps(final_data)}\n\n"
            yield "data: [DONE]\n\n"

        except Exception:
            logger.exception("Error in stream event_generator")
            error_data = {
                "error": {
                    "message": "Internal server error",
                    "type": "server_error",
                }
            }
            yield f"data: {json.dumps(error_data)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.get(
    "/health", response_model=HealthResponse, summary="Health check", tags=["Health"]
)
async def health():
    initialized = agent_graph_closure is not None
    body = {"status": "healthy" if initialized else "not_ready", "agent_initialized": initialized}
    if not initialized:
        return JSONResponse(status_code=503, content=body)
    return body


# ── Playground UI ────────────────────────────────────────────────────────────
_BASE_DIR = Path(__file__).resolve().parent
_PLAYGROUND_HTML = _BASE_DIR / "playground" / "templates" / "index.html"
# In Docker the images are copied to /opt/app-root/src/images; locally they live at the repo root
_IMAGES_DIR = _BASE_DIR / "images"
if not _IMAGES_DIR.is_dir():
    _IMAGES_DIR = _BASE_DIR.parent.parent.parent / "images"


@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def playground():
    """Serve the playground chat UI."""
    return FileResponse(_PLAYGROUND_HTML)


@app.get("/images/{filename:path}", include_in_schema=False)
async def serve_image(filename: str):
    """Serve images from the project-level images directory."""
    base = _IMAGES_DIR.resolve()
    file_path = (base / filename).resolve()
    try:
        file_path.relative_to(base)
    except ValueError:
        raise HTTPException(status_code=404, detail="Image not found")
    if not file_path.is_file():
        raise HTTPException(status_code=404, detail="Image not found")
    return FileResponse(file_path)


if __name__ == "__main__":
    import uvicorn

    port = int(getenv("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
