{{- if .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "agent.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
