apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-automl
  labels:
    app: mcp-automl
spec:
  to:
    kind: Service
    name: mcp-automl
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
