apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-secret.yaml
  - 02-configmap.yaml
  - 03-pvc.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - 06-route.yaml

commonLabels:
  app.kubernetes.io/name: openclaw
  app.kubernetes.io/part-of: openclaw-on-openshift
